Testing builds through service containers in GitHub Actions
fosslight/fosslight pull request #1002
Opened 2023-10-04 15:47 UTC by yenawee

## Description

asis : build performed by docker compose
tobe: build performed by service container

서비스 컨테이너를 통해서 빌드하게 yml 파일을 수정했습니다
이것저것 테스트해보다가 이전 PR 이 닫혀서 부득이하게 새 PR 을 열었습니다
yml 파일 분리하는 것은 .github 레포지토리에 분리해야 할 거 같아서 우선 분리하지 않았습니다

issue #985 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2023-10-04 16:03 UTC, jongwooo requested changes

2023-10-04 16:03 UTC, jongwooo commented on .github/workflows/pull-request.yml
@yenawee 님, DB와 메일서버 컨테이너 실행도 필요합니다. `docker-compose.yml`을 참고하시어 services에 추가 부탁드립니다.

2023-10-05 06:19 UTC, yenawee commented on .github/workflows/pull-request.yml
죄송합니다!
docker-compose.yml 참고해서 DB 랑 메일 서버도 services 에 추가했는데 동작할질 모르겠습니다 ㅠㅠ
깃허브 액션 플로우가 동작하는지 테스트를 해보는게 넘 어렵네요....

2023-10-05 06:22 UTC, jongwooo commented on .github/workflows/pull-request.yml
@yenawee [act](https://github.com/nektos/act)를 활용하시면 로컬에서도 테스트 해보실 수 있습니다. 진행하시면서 어려운 점 있으시면 알려주세요:)

2023-10-06 07:41 UTC, soimkim commented
테스트 완료되면 Ready for review 클릭 부탁드립니다.

2023-10-06 07:47 UTC, 70825 commented on .github/workflows/pull-request.yml
저는 다른 오픈소스에 기여할 때 act를 사용하는게 처음이라 계속 에러가 나와서 포크한 리포지토리에 PR 날려서 워크플로우 잘 돌아가는지 테스트 했었어요 😅
비효율적인 방법이긴한데 참고하시길 바래요

2023-11-12 00:34 UTC, closed without merging