Add license inquiry function using github API
fosslight/fosslight pull request #269
Opened 2021-11-17 06:49 UTC by riyenas0925

Signed-off-by: riyenas0925 <riyenas0925@gmail.com>
 license inquiry function using github API (not oss version and download location)

### test file
[TEST Github.xlsx](https://github.com/fosslight/fosslight/files/7552361/TEST.Github.xlsx)

### result
![image](https://user-images.githubusercontent.com/32615702/142148769-5792c807-26ca-485a-a21c-14b3654dfaae.png)

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2021-11-18 08:12 UTC, riyenas0925 commented
[Github Test.xlsx](https://github.com/fosslight/fosslight/files/7561149/Github.Test.xlsx)

2021-11-18 08:50 UTC, riyenas0925 commented
# Test OSS List (github token is required for testing))
* [Exist DB.xlsx](https://github.com/fosslight/fosslight/files/7561391/Exist.DB.xlsx)
* [Clearly Defined Test.xlsx](https://github.com/fosslight/fosslight/files/7561392/Clearly.Defined.Test.xlsx)
* [Github Test.xlsx](https://github.com/fosslight/fosslight/files/7561393/Github.Test.xlsx)

2021-11-25 04:32 UTC, soimkim commented
[SelfCheck-Report-1-test_20211125.xlsx](https://github.com/fosslight/fosslight/files/7600181/SelfCheck-Report-1-test_20211125.xlsx)
<img width="756" alt="스크린샷 2021-11-25 오후 1 29 10" src="https://user-images.githubusercontent.com/4284712/143379891-dca368b4-ab05-47a5-9c52-2969fec6304b.png">
When I click Check License with above data, an error pops up and it loads infinitely.

![image](https://user-images.githubusercontent.com/4284712/143379942-da53533b-f8db-493b-84b8-64bd287bcaf1.png)

2021-11-25 08:45 UTC, soimkim requested changes

2021-11-25 08:45 UTC, soimkim commented on src/main/java/oss/fosslight/common/DependencyType.java
> +package oss.fosslight.common;
Please add copyright, license text

2021-11-25 08:45 UTC, soimkim commented on src/main/java/oss/fosslight/common/ExternalServiceType.java
> +package oss.fosslight.common;
Please add copyright, license text

2021-11-25 08:58 UTC, soimkim approved these changes

2021-11-25 08:59 UTC, merged