Ctask seonghoon
fosslight/fosslight pull request #648
Opened 2022-08-31 06:55 UTC by swa07016

## Description

Remove SPDX format in Packaging > Notice and Self-Check List > Notice.

### Previous UI
- Packaging > Notice
![Untitled](https://user-images.githubusercontent.com/53550707/187612013-113f5032-3427-441c-980e-01851769b78c.png)

- Self-Check List > Notice
![KakaoTalk_Photo_2022-08-31-15-50-42](https://user-images.githubusercontent.com/53550707/187612385-8227c9b3-4940-4e1d-9e5f-4b8a029cdabc.jpeg)

### Current UI
- Packaging > Notice
<img width="1086" alt="Untitled (1)" src="https://user-images.githubusercontent.com/53550707/187612634-5e0236a3-4679-42e4-b39b-b74e4a58f4fe.png">

- Self-Check List > Notice
<img width="1070" alt="Untitled (2)" src="https://user-images.githubusercontent.com/53550707/187612762-2a127afc-8757-4d4a-9bad-5cdb0ae84c07.png">

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2022-08-31 11:58 UTC, soimkim commented
This PR can be merged when SPDX is added to the Export button.

2022-09-17 11:31 UTC, soimkim requested changes
@swa07016 ,
https://github.com/fosslight/fosslight/pull/664 이 동작하기 위해서 다운로드 function을 삭제하지 말고 UI 상에서만  Notice 탭에서 SPDX 다운로드 list를 삭제해야 합니다. 
본 PR이 반영되어도 https://github.com/fosslight/fosslight/pull/650, https://github.com/fosslight/fosslight/pull/664 가 동작하는 지 확인 부탁드립니다.

2022-09-18 13:57 UTC, swa07016 commented
> @swa07016 , #664 이 동작하기 위해서 다운로드 function을 삭제하지 말고 UI 상에서만 Notice 탭에서 SPDX 다운로드 list를 삭제해야 합니다. 본 PR이 반영되어도 #650, #664 가 동작하는 지 확인 부탁드립니다.

넵 확인 후 반영해보겠습니다!

2022-09-20 03:18 UTC, swa07016 commented
> > @swa07016 , #664 이 동작하기 위해서 다운로드 function을 삭제하지 말고 UI 상에서만 Notice 탭에서 SPDX 다운로드 list를 삭제해야 합니다. 본 PR이 반영되어도 #650, #664 가 동작하는 지 확인 부탁드립니다.
> 
> @soimkim 넵 확인 후 반영해보겠습니다!

@soimkim #664 에서 다운로드 함수를 호출하므로 해당 함수들을 지웠던 커밋을 삭제하였습니다.

2022-09-20 06:41 UTC, 70825 commented
@swa07016 여기 PR에서 삭제되었던 다운로드 함수는 project 페이지에서 작동하는 코드로 알고 있습니다. 그래서 #664 에 있는 코드는 selfcheck 페이지와 관련이 있는 코드라 정상적으로 작동이 되는 것으로 알고 있는데 혹시 확인이 된 것 인가요?

2022-09-21 03:53 UTC, swa07016 commented
> @swa07016 여기 PR에서 삭제되었던 다운로드 함수는 project 페이지에서 작동하는 코드로 알고 있습니다. 그래서 #664 에 있는 코드는 selfcheck 페이지와 관련이 있는 코드라 `project` > `verification-js.jsp` 코드를 삭제해도 정상적으로 작동이 되는 것으로 알고 있는데 혹시 확인이 된 것 인가요?

제가 edit-js.jsp에서 삭제했다고 생각했었네요😂 다시 돌려두었습니다.

2022-09-21 04:26 UTC, soimkim commented
https://github.com/fosslight/fosslight/pull/650, https://github.com/fosslight/fosslight/pull/664 Merge되면 본 PR 테스트 후 머지하겠습니다. 😄

2022-09-25 05:09 UTC, soimkim approved these changes

2024-01-05 09:08 UTC, soimkim commented
Deferred

2024-01-05 09:08 UTC, closed without merging