Highlight Oss data failed to save in red
fosslight/fosslight pull request #721
Opened 2022-10-08 12:06 UTC by yujung7768903

## Summary
Change background color of oss that failed to save in bulk registration.
## Description

1. Add `failOss` variable in `ossBulkReg-js.jsp` to save failed data as list.
2. Modified response body of "/oss/bulkRegAjax" API.
* Previous response body
```json
{
    "res":true,
    "value":[
        {
	    "gridId": "1", 
            "status": "O"
        },
        {
	    "gridId": "2", 
	    "status": "X (error message)", 
        }
    ]
}
```
* After response body
```json
{
    "res":true,
    "value":[
        {
	    "gridId": "1", 
            "status": true,
            "msg": "O"
        },
        {
	    "gridId": "2", 
	    "status": false,
	    "msg": "X (error message)"
        }
    ]
}
```

## Result
### Previous UI
![fosslight-previous-ui](https://user-images.githubusercontent.com/68562176/194705296-2a728869-598d-4aa6-977c-7bf56d880e20.png)

### Current UI
https://user-images.githubusercontent.com/68562176/194705385-5f4b1289-773c-4e95-948a-2488acde8af6.mov

## Process
(Add `failOss` variable to save failed data as list)
1. Import excel.
2. Initalize `failOss`.
4. Save oss data in bulk.
5. Save failed data in `failOss` while checking results in loop(Check for failure with the `status` variable).
6. Change the background color of failed data rows in `failOss` loop in `makeBackgroundColor()` function.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2022-10-08 12:16 UTC, yujung7768903 commented
## 변경사항
1. 대량 저장에서 실패한 데이터를 리스트로 저장하기 위해 `failOss` 변수를 추가했습니다.
2. "/oss/bulkRegAjax" API의 response body 형태를 변경했습니다. 
기존 `status`에 담겼던 값은 `msg`변수에 저장           
→ `gridId`: 행의 아이디, `status`는 실패여부에 대해 참 또는 거짓 값, `msg`: status 컬럼에 들어갈 메세지

## 로직
1. 엑셀 임포트
2. `failOss` 변수 초기화.
4. 대량으로 오픈소스 데이터 저장.
5. 저장 결과를 반복문으로 돌면서 저장에 실패한 데이터를 `failOss` 변수에 저장.(저장 실패여부는 boolean 타입의 `status`변수를 통해 체크).
6. `makeBackgroudColor()` 메서드안에서 `failOss`를 반복문으로 돌면서 실패한 데이터의 행 색상 변경

2022-10-09 07:09 UTC, FRESH-TUNA requested changes
작업하시느라고 고생많으셨습니다!
작업하신 코드에 대해 설명하는 주석을 달아주시면 좋을것 같습니다!

2022-10-09 07:09 UTC, FRESH-TUNA commented on src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
> +                row.msg = ""
Please rollback `msg` to `status`.
`cleanStatusMessages` function empty status field of Table.

2022-10-09 07:09 UTC, FRESH-TUNA commented on src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
> +        console.log("failOss: ", failOss.toString());
Please remove `console.log` to test purposes.

2022-10-11 11:39 UTC, FRESH-TUNA approved these changes
L.G.T.M !

2022-10-12 02:28 UTC, merged