[#821] Project > Basic Information > Drop > Show comment popup
fosslight/fosslight pull request #856
Opened 2023-06-15 03:13 UTC by yenawee

## Description

Show comment pop-up with editor when dropping project.

BEFORE

![](https://user-images.githubusercontent.com/102017711/220521980-9a4423bc-d0c5-4db6-a8cc-fbb18a766ec1.png)

AFTER
<img width="500" alt="스크린샷 2023-06-15 오후 12 11 25" src="https://github.com/fosslight/fosslight/assets/91937954/b3828de0-004a-4aa4-830b-613c2e5fb7e6">

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

If there is something to be fixed, please let me know!

2023-06-16 05:41 UTC, jongwooo requested changes
@yenawee Thank you for your contribution!

Please write about what you did in the commit message. (e.g. `Show comment pop-up with editor when dropping project`) 

The following command may be helpful:

```bash
git commit --amend
```

And since [bddf57d](https://github.com/fosslight/fosslight/pull/856/commits/bddf57d0f9ead85137ad87280180cadd673f4573) and [72877bc](https://github.com/fosslight/fosslight/pull/856/commits/72877bc52cadf811b28780d01117e71c455a66fb) currently have the same commit message, consider combining them into one commit with squash:)

2023-06-16 11:16 UTC, yenawee commented
@jongwooo Thank you
I have updated the git commit history :)

2023-06-16 11:19 UTC, jongwooo approved these changes

2023-07-26 12:07 UTC, 70825 approved these changes

2023-07-30 05:38 UTC, soimkim commented
AS-IS에서는 Comment 에 남긴 사항이 Dropped 커맨트에 남습니다.
<img width="889" alt="image" src="https://github.com/fosslight/fosslight/assets/4284712/0e30487e-7a3a-4e99-a757-639708dc5997">

그러나 TO-BE에서는 Comment에 남긴 사항이 Dropped에 남지 않습니다.

2023-07-30 07:15 UTC, yenawee commented
확인 감사합니다!!

추가 수정 후 PR 올리겠습니다

2023-08-17 23:41 UTC, soimkim commented
@yenawee , 추가 수정 진행 여부 문의드립니다.

2023-09-05 01:00 UTC, 70825 reviewed
Can you make commit messages 50 characters or less in length?

2023-10-04 15:25 UTC, closed without merging

2023-10-05 04:36 UTC, soimkim commented
@yenawee , 해당 PR 삭제된 것으로 보입니다. 별도 PR에서 진행하시나요?

2023-10-05 12:55 UTC, yenawee commented
포크한 레포를 삭제하고 다시 받는 과정에서 PR 이 닫혔습니다..!
해당 건 바로 진행하지 못할 거 같아 별도 PR 에서 진행하지 않고 있습니다

2023-10-06 04:23 UTC, soimkim commented
@yenawee , 답변 감사합니다. :-) 해당 이슈 Assignee : 없음으로 변경했습니다.