Feature/351
fosslight/fosslight pull request #888
Opened 2023-07-18 12:49 UTC by d-h-k

## Description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2023-08-18 00:57 UTC, soimkim requested changes

2023-08-18 00:57 UTC, soimkim commented on db/initdb.d/fosslight_create.sql
> +    ('227', '1', '15', '', '', 15,'Y')
@moto3z, `,` 가 없어서 에러 날 것으로 보입니다.

2023-08-18 00:58 UTC, soimkim commented
@moto3z , db/initdb.d/fosslight_create.sql 수정시에는 https://github.com/fosslight/fosslight/blob/develop/migration/migration/scripts/20230818004358_update_v1.6.1.sql 도 수정해주십시오.

2023-08-18 01:11 UTC, soimkim commented
@moto3z , 수정 완료되면 Ready for review 클릭해주십시오.

2023-10-06 00:32 UTC, moto3z commented
@soimkim 안녕하세요 소임님! 피드백주신 내용 반영해서 새로운 PR 로 다시 작성해서 만들었습니다.  
(새로운 PR 링크 : https://github.com/fosslight/fosslight/pull/1004)

그래서 혹시 해당 PR 은 close 처리를 부탁드려도 될까요?

2023-10-06 01:37 UTC, closed without merging

2023-10-06 01:37 UTC, jongwooo commented
Superseded by #1004.