Refactoring for deprecated Slack code
fosslight/fosslight pull request #930
Opened 2023-07-29 13:01 UTC by che-so

## Description
I found deprecated code in /github/workflows/release-publish.yml.

We've been informed that we're not using Slack this year. We decided it would be more efficient for the program to remove unused features.

AS-IS:
Slack Workflow Notification feature still exists in program code even though it's disabled

TO-BE:
Remove unused Slack Workflow Notification features

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2023-07-29 13:05 UTC, jongwooo commented
@che-so Consider changing the title to 'Remove unused Slack notification step'.

2023-07-29 13:08 UTC, jongwooo requested changes
Also, the commit in [d766f93](https://github.com/fosslight/fosslight/pull/930/commits/d766f9379ddf2c76e79ce9d312a11940da3fc934) seems to be unrelated to the issue. Only relevant commits should be included in the pull request.

2023-07-30 10:55 UTC, 70825 approved these changes

2023-07-30 16:06 UTC, jongwooo requested changes

2023-07-30 16:06 UTC, jongwooo commented on .github/workflows/release-publish.yml
> +          cache-to: type=gha,mode=max
In the POSIX standard, a line is defined as: `A sequence of zero or more non- <newline> characters plus a terminating <newline> character`. We should follow this standard and add a newline at the end of a file.

```suggestion
          cache-to: type=gha,mode=max
```

2023-08-07 06:59 UTC, soimkim commented on .github/workflows/release-publish.yml
> +          cache-to: type=gha,mode=max
@che-so 님, 종우님 커맨트 확인 후 수정 완료되시면 Resolve conversation해주십시오.

2023-08-09 14:56 UTC, jongwooo requested changes

2023-08-15 16:20 UTC, jongwooo approved these changes
@che-so LGTM. Thanks😃

2023-08-19 06:39 UTC, merged