Jib를 통해 이미지 생성
fosslight/fosslight pull request #996
Opened 2023-09-26 12:26 UTC by Gseungmin

도커 파일을 통해 이미지 빌드하는 방식을 Jib로 변경

## Description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2023-09-29 05:13 UTC, jongwooo commented
@Gseungmin Consider changing the title to 'Build docker image with Jib'.

2023-10-06 07:39 UTC, soimkim requested changes
커맨트로 문의드린 사항에 대해 답변 부탁드립니다.

2023-10-06 07:39 UTC, soimkim commented on docker-compose.yml
> +    image: fosslight/fosslight
@Gseungmin , 이 수정의 경우, 현재 소스 기반으로 build하는 것이 아닌 dockerhub에 배포된 이미지를 가져오는 것 아닌가요?
docker-compose.yml은 개발시 활용되는 case가 많아 현재 소스 기반으로 빌드 및 실행이 더 좋아보입니다.

2023-10-06 08:17 UTC, Gseungmin commented on docker-compose.yml
> +    image: fosslight/fosslight
I changed It!

2023-11-09 09:47 UTC, merged